### ISSUE TITLE
Separate download links

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-sans#155] opened 2016-06-09 19:42 UTC
1.6GB is huge.
Separate them into “OTC” “OTF” “Source” etc.

**Comment by kenlunde** [comment] 2016-06-09 19:49
This is the main reason why the OTC, OTF, and SubsetOTF directories include ZIP files that include collections of font resources, and the landing page has convenient links to these ZIP files. This is sort of a duplicate of Issue #64.

**Closed by kenlunde** 2016-06-09 19:49 UTC
Labels: as designed

**Comment by hfhchan** [comment] 2016-06-09 19:57
I've come across this issue not less than once, and found it annoying I have manually switch to the release branch -- this is not that common for cloning open source projects.

I just checked the readme on the master branch and only realized now that the word "release" is clickable in "You can either download entire releases after clicking one of the two links below, or go to this project's release branch to download individual font resources or ZIP files that include all weights for a particular language or region-specific subset:".

Meanwhile, the links Latest Release and All Releases point to the full zip.

It seems less obvious to have the preferred choice be put inline and less preferred choices be listed over two lines (with padding before and after).  It might easily mislead people.

**Comment by hfhchan** [comment] 2016-06-09 20:16
I suggest the text:
> Note that if you click the Download ZIP button for this project that the download size of the current version is approximately 1.2GB for the master branch, and approximately 1.6GB for the release branch.
> You can either download entire releases after clicking one of the two links below, or go to this project's release branch to download individual font resources or ZIP files that include all weights for a particular language or region-specific subset:
> - Latest release
> - All releases
> For information about the various deployment configurations, and to help decide which fonts to download, please refer to the Configurations section of the official font readme file.


be amended to

> Individual font resources or ZIP files for various deployment configurations are available for download.
> - Latest Release *(link this to the release branch)*
>
> To help decide which fonts to download, please refer to the Configurations section of the official font readme file.
>
> You can also download entire releases *(link this to the releases page)* which includes all available configurations in one ZIP file.  The latest release  *(link this to the latest releases page)*  is over 1.2 GB.

**Comment by kenlunde** [comment] 2016-06-10 01:19
@hfhchan: Thank you. I will make some adjustments to the landing page of the _master_ branch per your suggestions in the next day or two.

**Comment by kenlunde** [comment] 2016-06-10 14:40
@hfhchan: Done, though I adjusted some of the wording a bit.
