### ISSUE TITLE
Embedded Errors

### ISSUE THREAD

**Issue by allen5261** [adobe-fonts/source-han-sans#184] opened 2017-08-10 02:35 UTC
@kenlunde Why I cannot embed the font `Source Han Sans` and `Source Han Serif` into Microsoft PowerPoint Document, the program said:
![tim 20170810103050](https://user-images.githubusercontent.com/25821197/29151996-3f4e4d8e-7db7-11e7-9015-ef281ab910f0.png)

How can I solve this problem? Thanks.

**Comment by kenlunde** [comment] 2017-08-10 02:40
This is a duplicate of Issue #87, which references [this document](https://support.microsoft.com/en-us/help/908475/you-cannot-embed-an-adobe-opentype-font-in-a-document-in-an-office-pro) from our friends over at Microsoft.

**Closed by kenlunde** 2017-08-10 02:40 UTC
Labels: not this product
