### ISSUE TITLE
Interpolating new weights?

### ISSUE THREAD

**Issue by davelab6** [adobe-fonts/source-han-sans#149] opened 2016-05-06 22:06 UTC
Is it possible to interpolate a new/custom instance with the publicly available tools? 

I couldn't find the MM file...

**Comment by kenlunde** [comment] 2016-05-06 22:27
This is a duplicate of #119. Too many processes have been applied to the master weights, ExtraLight and Heavy (equivalent to Thin and Black in Noto Sans CJK), making them no longer compatible in terms of interpolation.

**Closed by kenlunde** 2016-05-06 22:27 UTC
Labels: duplicate

**Comment by davelab6** [comment] 2016-05-06 22:34
That makes sense :) Thanks!
